emitClient player array support
altmp/altv-js-module pull request #41
Opened 2021-05-18 21:46 UTC by tastydev

example:

```
//sent to all players inside array
alt.emitClient([player, player, player], 'client:testEvent', "test5", 4);
//sent to specific player
alt.emitClient(player, 'client:testEvent', "test5", 4);
//sent to all players
alt.emitClient(null, 'client:testEvent', "test5", 4);
```

2021-05-18 21:48 UTC, FabianTerhorst commented on src/bindings/Main.cpp
> +	if (!info[0]->IsNull() && info[0]->IsArray())
you sure the IsNull is needed? Because when its a array it can't really be Null.

2021-05-18 22:11 UTC, tastydev commented on src/bindings/Main.cpp
> +	if (!info[0]->IsNull() && info[0]->IsArray())
i did it to be save but i can actually remove it cause the if on top of that if checks for isNull() already

2021-05-18 22:42 UTC, tastydev commented
altmp/altv-issues#948

2021-05-19 11:01 UTC, LeonMrBonnie commented on src/bindings/Main.cpp
> +	if (!info[0]->IsNull() && info[0]->IsArray())
The `Is*` calls only ever return true for one of them, so the `IsNull` is/was unnecessary here

2021-05-19 11:03 UTC, LeonMrBonnie requested changes
Please use the brace style as in the rest of the module, so braces always go on their own line

2021-05-19 16:06 UTC, LeonMrBonnie reviewed
Did you test if this works?

2021-05-19 16:21 UTC, tastydev commented
yes it works without any issues

2021-05-19 16:22 UTC, LeonMrBonnie approved these changes

2021-05-19 16:27 UTC, merged